#!/usr/bin/env bash
#
# Build web-optimised derivatives from the master photos.
#
#   ./scripts/build-images.sh [SOURCE_DIR]
#
# SOURCE_DIR defaults to $PHOTO_MASTERS or ../peterandconsuelo-photo-masters.
# The masters are deliberately kept outside the repo; only the derivatives in
# assets/photos/ are committed and deployed to GitHub Pages.
#
# Requires: sips (macOS built-in) and cwebp (brew install webp).

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="${1:-${PHOTO_MASTERS:-$ROOT/../peterandconsuelo-photo-masters}}"
OUT="$ROOT/assets/photos"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

# name:max-edge:quality
VARIANTS=(thumb:240:68 md:1000:74 lg:1800:78)

command -v cwebp >/dev/null || { echo "cwebp not found — brew install webp" >&2; exit 1; }
[ -d "$SRC" ] || { echo "source dir not found: $SRC" >&2; exit 1; }

for v in "${VARIANTS[@]}"; do mkdir -p "$OUT/${v%%:*}"; done

# Resize + encode one variant of one file. Skips work that is already done.
convert_one() {
  local src="$1" variant="$2" max="$3" q="$4" out tmp
  out="$OUT/$variant/$(basename "${src%.*}").webp"
  [ -f "$out" ] && [ "$out" -nt "$src" ] && return 0
  tmp="$TMP/$variant-$(basename "$src")"
  sips --resampleHeightWidthMax "$max" "$src" --out "$tmp" >/dev/null 2>&1
  cwebp -quiet -q "$q" -m 6 -metadata none "$tmp" -o "$out" >/dev/null 2>&1
  rm -f "$tmp"
}
export -f convert_one
export OUT TMP

shopt -s nullglob nocaseglob
sources=("$SRC"/*.jpg "$SRC"/*.jpeg "$SRC"/*.png)
shopt -u nocaseglob
[ ${#sources[@]} -gt 0 ] || { echo "no images found in $SRC" >&2; exit 1; }

echo "Building ${#sources[@]} photos → $OUT"
for v in "${VARIANTS[@]}"; do
  IFS=: read -r name max q <<<"$v"
  echo "  $name (max ${max}px, q$q)…"
  printf '%s\0' "${sources[@]}" \
    | xargs -0 -P "$(sysctl -n hw.ncpu)" -I{} \
        bash -c 'convert_one "$@"' _ {} "$name" "$max" "$q"
done

# ---------------------------------------------------------------------------
# Manifest: id + intrinsic aspect ratio, so the slide box can be reserved
# before the image decodes (no layout shift, no flash of wrong size).
# ---------------------------------------------------------------------------
echo "  manifest…"
{
  echo "// Generated by scripts/build-images.sh — do not edit by hand."
  echo "window.PHOTOS = ["
  for src in "${sources[@]}"; do
    id="$(basename "${src%.*}")"
    read -r w h < <(sips -g pixelWidth -g pixelHeight "$src" \
      | awk '/pixelWidth/{w=$2} /pixelHeight/{h=$2} END{print w, h}')
    printf '  ["%s",%s,%s],\n' "$id" "$w" "$h"
  done
  echo "];"
} > "$ROOT/assets/js/photos.js"

echo
echo "Done. $(find "$OUT" -name '*.webp' | wc -l | tr -d ' ') files, $(du -sh "$OUT" | cut -f1) total."
